---

- name: install nginx
  pacman: name=nginx,nginx-mod-brotli state=present

- name: install nginx.service snippet
  copy: src=nginx.service.d dest=/etc/systemd/system owner=root group=root mode=0644

- name: configure nginx
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root group=root mode=0644
  notify:
    - restart nginx

- name: make nginx log dir
  file: path=/var/log/nginx/{{ server_http_domain }} state=directory owner=root group=root mode=0755

- name: snippets directories
  file: state=directory path=/etc/nginx/{{ item }} owner=root group=root mode=0755
  with_items:
    - toplevel-snippets
    - snippets

- name: copy snippets
  template: src={{ item }} dest=/etc/nginx/snippets owner=root group=root mode=0644
  with_items:
    - letsencrypt.conf
    - sslsettings.conf
  notify:
    - reload nginx

- name: install cert renewal hook
  template: src=letsencrypt.hook.d.j2 dest=/etc/letsencrypt/hook.d/nginx owner=root group=root mode=0755

- name: create nginx.d directory
  file: state=directory path=/etc/nginx/nginx.d owner=root group=root mode=0755

- name: create auth directory
  file: state=directory path=/etc/nginx/auth owner=root group=root mode=0755

- name: create default nginx log directory
  file: state=directory path=/var/log/nginx/default owner=root group=root mode=0755

- name: create unique DH group
  command: openssl dhparam -out /etc/ssl/dhparams.pem 2048 creates=/etc/ssl/dhparams.pem

- name: create directory to store validation stuff in
  file: owner=root group=http mode=0750 path={{ letsencrypt_validation_dir }} state=directory

- name: install logrotate config
  copy: src=logrotate.conf dest=/etc/logrotate.d/nginx-ansible owner=root group=root mode=0644

- name: install inventory_hostname vhost
  template: src=nginx-hostname-vhost.conf.j2 dest=/etc/nginx/nginx.d/nginx-hostname-vhost.conf owner=root group=root mode=0644
  notify:
    - reload nginx
  tags: ['nginx']

- name: enable nginx
  service: name=nginx enabled=yes

- name: Allow http connections
  ufw:
    rule: allow
    port: http
    proto: tcp

- name: Allow https connections
  ufw:
    rule: allow
    port: https
    proto: tcp

- name: set up nginx
  template: src=nginx.d.conf.j2 dest=/etc/nginx/nginx.d/domain.conf owner=root group=root mode=644
  notify:
    - reload nginx
  tags: ['nginx']

- name: create ssl cert
  command: certbot certonly --email webmaster@lsferreira.net --agree-tos --rsa-key-size 4096 --renew-by-default --webroot -w {{ letsencrypt_validation_dir }} -d '{{ server_http_domain }}' creates='/etc/letsencrypt/live/{{ server_http_domain }}/fullchain.pem'
  when: 'server_http_domain is defined'
