---

- name: create mount directories
  file:
    path: '{{ item.mount_point }}'
    state: directory
    recurse: yes
  with_items: '{{ raid_disks }}'

- name: Mount RAID disks
  mount:
    path: '{{ item.mount_point }}'
    src: '{{ item.device }}'
    fstype: '{{ item.type }}'
    state: mounted
  with_items: '{{ raid_disks }}'
