# roles/samba/vars/os_Archlinux.yml
---

samba_packages:
  - samba
  - smbclient

samba_services:
  - smb
  - nmb

samba_configuration_dir: /etc/samba
samba_configuration: "{{ samba_configuration_dir }}/smb.conf"
