---

- name: Install java chocolatey packages
  win_chocolatey:
    name: '{{ item }}'
    state: present
  with_items:
    - openjdk
    - openjdk12
    - openjdk11
    - openjdk8
    - jdk11
    - jdk8
    - javaruntime
    - jre8
