---

- name: install aur packages
  hosts:
    - mars.lsferreira.net
    - deimos.lsferreira.net
  roles:
    - { role: aur, tags: ['aur'] }
    - { role: yay, tags: ['yay'] }
    - { role: aur_packages, tags: ['aur_packages'] }
