---

- name: common setup playbook
  hosts:
    - all
    - '!phobos.lsferreira.net'
  roles:
    - { role: common, tags: ['common'] }
    - { role: users, tags: ['users'] }
    - { role: ssh_root, tags: ['ssh_root'] }
    - { role: sudo, tags: ['sudo'] }
    - { role: firewall, tags: ['firewall'] }
    - { role: archbuild, tags: ['archbuild'] }
