---

- name: setup luna
  hosts: 192.168.1.1
  roles:
    - { role: common, tags: ['common'] }
    - { role: users, tags: ['users'] }
    - { role: ssh_root, tags: ['ssh_root'] }
    - { role: sudo, tags: ['sudo'] }
    - { role: hardening, tags: ['hardening'] }
    - { role: tools, tags: ['tools'] }
    - { role: firewall, tags: ['firewall'] }
    - { role: archbuild, tags: ['archbuild'] }
    - { role: named, tags: ['named'] }
    - { role: syncrepo, tags: ['syncrepo'] }
    - { role: lighttpd, tags: ['lighttpd'] }
    - { role: openvpn, tags: ['openvpn'] }
    - { role: yay, tags: ['yay'] }
    - { role: certbot, tags: ['certbot'] }
    - { role: grafana, tags: ['grafana'] }
    - { role: nginx, tags: ['nginx'] }
    - { role: docker, tags: ['docker'] }
    - { role: docker_services, tags: ['docker_services'] }
